### PR TITLE
Added a toggle to show/hide and copy the code for the calendar

### PR DESCRIPTION
**Pull request by nimishjain77**
- Added an Accordion to show/hide and copy the code for the calendar.
- Shown Accordion on the left menu.
- Fixed accordian issues related to opening/closing.
- Fixed CSS for material table.
- Copy code will copy only the HTML code for the use case.

[screencast-localhost_4200-2023.11.09-16_54_45.webm](https://github.com/lokeshdaiya-yash/PTG-UI-Library/assets/150128770/68c16c57-e47b-4864-8a15-52056d4023f8)

### CODE REVIEW

**Comment by ZalawaHarsha** [comment]
@nimishjain77  Can we add tabs for each file ? right now all the code is part of accordion and when we copy both html and typescript will be copied. We can give option to copy individual section.

**Comment by nimishjain77** [comment]
@ZalawaHarsha Well, the Copy icon is copying only the HTML part, Not for the typescript, Component part is just to showcase what variable value we are using in the HTML.
and to add tabs, we need to add different packages for that because I didn't see anything implemented in PTG lib similar to that.

**Comment by ZalawaHarsha** [comment]
> @ZalawaHarsha Well, the Copy icon is copying only the HTML part, Not for the typescript, Component part is just to showcase what variable value we are using in the HTML. and to add tabs, we need to add different packages for that because I didn't see anything implemented in PTG lib similar to that.

Yes as of now we don't have component. Either you can create new component in Lib or use third party library as this is part of demo application. We can have design similar to attached image 


image

**Comment by nimishjain77** [comment]
@ZalawaHarsha Okay. I will use a tab structure to display HTML and TS.

**Comment by nimishjain77** [comment]
@lokeshdaiya @ZalawaHarsha 
I've updated the code for Calendar component as per the requirement.

- Added toggle to Show/Hide code for the calendar component.
- Removed accordion and used toggle for that.
- Added tabs to display HTML & TS code
- Copy code functionality for HTML & TypeScript

[screencast-localhost_4200-2023.11.23-19_04_12.webm](https://github.com/lokeshdaiya-yash/PTG-UI-Library/assets/150128770/7d79b526-cf39-40c6-8017-2b2ae95fa331)

**Comment by nimishjain77** [comment]
@lokeshdaiya-yash 
Made a common component for Toggling the code and code snippet shows in the highlighted panel.

[screencast-localhost_highlight.webm](https://github.com/lokeshdaiya-yash/PTG-UI-Library/assets/150128770/63eca537-6a64-4c41-9a05-8613a421027d)

**Pull request merged**
